In [ ]:
import numpy as np
import pandas as pd
from numpy import random

In [ ]:
import numpy as np
import pandas as pd
from numpy import random

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df=pd.read_csv("sample_data.csv")
df

x=np.array(df["YearsExperience"])
y=np.array(df["Salary"])

x,y

X=np.array([1,2,3])
Y=np.array([4,5,6])
print(np.dot(X,Y))

x_max=x.max()
x_min=x.min()
x_mean=x.mean()
x_std_dev=np.sqrt((np.sum((x-x_mean)*(x-x_mean)))/len(x))

for i in range(len(x)):
    x[i]=(x[i]-x_mean)/x_std_dev

y_max=y.max()
y_min=y.min()
y_mean=y.mean()
y_std_dev=np.sqrt((np.sum((y-y_mean)*(y-y_mean)))/len(y))

for i in range(len(y)):
    y[i]=(y[i]-y_mean)/y_std_dev

lr=0.01
epochs=100
w=b=0
for i in range(epochs):
    w_slope= -2*np.dot((y-w*x-b),x)
   
    b_slope=-2*np.sum((y-w*x-b))
    
    w=w-lr*w_slope
    b=b-lr*b_slope
    
x_plot=np.arange(-2,2,0.1)
y_plot=w*x_plot+b
plt.scatter(x,y)
plt.plot(x_plot,y_plot)
plt.show()


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [12]:
df=pd.read_csv("sample_data.csv")

In [14]:
x=np.array(df["YearsExperience"])
y=np.array(df["Salary"])

In [30]:
x,y

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [16]:
X=np.array([1,2,3])
Y=np.array([4,5,6])
print(np.dot(X,Y))

32


In [17]:
x_max=x.max()
x_min=x.min()
x_mean=x.mean()
x_std_dev=np.sqrt((np.sum((x-x_mean)*(x-x_mean)))/len(x))

for i in range(len(x)):
    x[i]=(x[i]-x_mean)/x_std_dev

In [18]:
y_max=y.max()
y_min=y.min()
y_mean=y.mean()
y_std_dev=np.sqrt((np.sum((y-y_mean)*(y-y_mean)))/len(y))

for i in range(len(y)):
    y[i]=(y[i]-y_mean)/y_std_dev

In [19]:
x,y

(array([-1.51005294, -1.43837321, -1.36669348, -1.18749416, -1.11581443,
        -0.86493538, -0.82909552, -0.75741579, -0.75741579, -0.57821647,
        -0.50653674, -0.47069688, -0.47069688, -0.43485702, -0.29149756,
        -0.1481381 , -0.07645838, -0.00477865,  0.21026054,  0.2461004 ,
         0.53281931,  0.6403389 ,  0.92705781,  1.03457741,  1.21377673,
         1.32129632,  1.50049564,  1.5363355 ,  1.78721455,  1.85889428]),
 array([-1.36011263, -1.10552744, -1.419919  , -1.20495739, -1.33978143,
        -0.71830716, -0.58815781, -0.79981746, -0.42881019, -0.69801306,
        -0.47433279, -0.74976858, -0.70662043, -0.70201994, -0.55250402,
        -0.29921736, -0.37004264,  0.26285865,  0.19885989,  0.66547573,
         0.58377993,  0.82623317,  0.93861127,  1.40274136,  1.24020308,
         1.09740238,  1.51986835,  1.3590738 ,  1.72102849,  1.70177321]))

In [21]:
lr=0.01
epochs=100
w=b=0
for i in range(epochs):
    w_slope= -2*np.dot((y-w*x-b),x)
   
    b_slope=-2*np.sum((y-w*x-b))
    
    w=w-lr*w_slope
    b=b-lr*b_slope
    
    

x_plot=np.arange(-2,2,0.1)
y_plot=w*x_plot+b
plt.scatter(x,y)
plt.plot(x_plot,y_plot)
plt.show()
